### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false


### content configuration ###
title:       "Radical Framework"
keywords:    "Radical, MVVM, WPF, Universal Apps"
description: "Radical is an infrastructure framework whose primary role is to help in the development of composite WPF and Universal applications based on the Model-View-ViewModel pattern."
source_link: "https://github.com/RadicalFx/RadicalFx.github.io"

theme: jekyll-theme-minimal

google_analytics: UA-92229383-1